### ISSUE TITLE
COCOA

### ISSUE THREAD

**Issue by ivorausch** [LalithShiyam/QIMP-tools#6]
**Describe the bug**
COCOA breaks after Bilinear scaling is done: 
Error message: Undefined function or variable 'ReadDicomElementList'.

Guess function ReadDicomElementList is missing ;)

Can you add this fuction?
Best,
I

**Comment by LalithShiyam** [comment]
Hi, Thanks for the notification. I have added the missing function. 
It should work now. 
Cheers.

**Comment by ivorausch** [comment]
Thanks for adding... now next issue:
I think the DicomTagDictionary.mat is missing. Should be in COCOA\Codes\Dictionary\ (guess this is a Foler?)
Perhaps I do also need to replace the "/" (Linux / Mac) with the "\" (windows). But I do not see the directory at all in the folder...

Here we go with a part of the Matlab output:
-------------
Coregistration done!
Low-dose CT to u-map conversion parameters: 9.6e-05, 5.1e-05, 0.0471, 1047!
Bilinear scaling done based on carney 2006...
Error using load
Unable to read file 'C:\Users\IR\Documents\MATLAB\COCOA\Codes\Dictonary/DicomTagDictionary.mat'. No such file or directory.

Error in ReadDicomElementList (line 60)
load([functiondir 'Dictonary/DicomTagDictionary.mat']);

Error in pushDataToDicom (line 26)
    ImpInfo=ReadDicomElementList(dicomImages(lp).name); % store the structs which are generated by dicomdisp

Error in pipelineForAleja (line 126)
pushDataToDicom(pathOfMRumap,CTuMap);

Error in wrapperPipelineForAleja (line 5)
pipelineForAleja(pfaInputs);

Cheers, 
I

**Comment by LalithShiyam** [comment]
Hi done.

**Comment by LalithShiyam** [comment]
Hi, I assume that the issue is handled and I am closing this issue due to lack of inactivity.
